apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: kanni-ai
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: 'kubernetes-pods'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  action: keep
                  regex: true

    processors:
      batch:
      resource:
        attributes:
          - key: service.name
            value: kanni-ai
            action: upsert

    exporters:
      prometheusremotewrite:
        endpoint: "https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push"
        headers:
          authorization: "Bearer YOUR_GRAFANA_PROMETHEUS_TOKEN"
      
      loki:
        endpoint: "https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push"
        headers:
          authorization: "Bearer YOUR_GRAFANA_LOKI_TOKEN"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [loki]
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch, resource]
          exporters: [prometheusremotewrite]
        logs:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [loki]