apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: kanni-ai
spec:
  image: otel/opentelemetry-collector-contrib:latest
  env:
    - name: GRAFANA_PROMETHEUS_TOKEN
      valueFrom:
        secretKeyRef:
          name: grafana-tokens
          key: prometheus-token
    - name: GRAFANA_LOKI_TOKEN
      valueFrom:
        secretKeyRef:
          name: grafana-tokens
          key: loki-token
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch: {}
      resource:
        attributes:
          - key: service.name
            value: kanni-ai
            action: upsert

    exporters:
      prometheusremotewrite:
        endpoint: "https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push"
        headers:
          authorization: "Bearer ${GRAFANA_PROMETHEUS_TOKEN}"
      
      loki:
        endpoint: "https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push"
        headers:
          authorization: "Bearer ${GRAFANA_LOKI_TOKEN}"
      
      debug:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [prometheusremotewrite, debug]
        logs:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [loki, debug]